pipeline {
    agent any
    stages {
        stage('Build Application') {
            steps {
                bat 'mvn -f java-tomcat-sample/pom.xml clean package'
            }
            post {
                success {
                    echo "Now Archiving the Artifacts...."
                    archiveArtifacts artifacts: '**/*.war'
                }
            }
        }

        stage('Deploy In Staging Environment') {
            steps {
                build job: ' Deploy_Application_Staging_Env'
            }
        }

         stage('Deploy In Production') {
            steps {
                timeout(time:5, unit:'DAYS') {
                input message: 'Approve Production Deployment ?'
                }
                build job: ' Deploy_Application_Prod_Env'
            }
        }
        
    }
}
